name: Run rhods-disconnected-helper script once a day

on: 
  schedule:
    - cron:  '0 12 * * *'

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Run rhods-disconnected-helper.sh script
      run: |
        chmod +x odh-nightlies-disconnected-helper.sh
        ./odh-nightlies-disconnected-helper.sh
      shell: bash
    - name: Commit and push changes to main branch
      uses: actions-js/push@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: main
        message: "Update rhods-disconnected-helper.sh script"
        repository: red-hat-data-services/rhods-disconnected-install-helper
